version = 0.1

[default.deploy.parameters]
stack_name = "llmops-pipeline"
resolve_s3 = true
s3_prefix = "llmops-pipeline"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
